/**
 * Client-safe tool display labels — no mongoose, no server imports.
 * Import this from client components instead of the main tools index.
 */

export const TOOL_LABELS: Record<string, string> = {
  search_knowledge: "Searching knowledge base",
  add_knowledge: "Saving to knowledge base",
  get_current_datetime: "Checking date & time",
  create_clickup_task: "Creating ClickUp task",
  list_clickup_tasks: "Listing ClickUp tasks",
  count_conversations: "Counting conversations",
  send_email: "Sending email",
  read_emails: "Reading emails",
  list_calendar_events: "Checking calendar",
  create_calendar_event: "Creating calendar event",
  get_leads: "Loading revenue pipeline",
  update_lead_status: "Updating lead status",
  get_daily_briefing: "Fetching daily briefing",
  search_vault: "Searching vault",
  read_vault_note: "Reading vault note",
  create_vault_note: "Creating vault note",
  list_vault_notes: "Listing vault notes",
  check_vps_status: "Checking VPS status",
  create_automation: "Creating automation",
  list_automations: "Listing automations",
  toggle_automation: "Toggling automation",
  add_transaction: "Recording transaction",
  get_finance_summary: "Loading finance summary",
  add_contact: "Adding contact",
  search_contacts: "Searching contacts",
  update_contact: "Updating contact",
  award_xp: "Awarding XP",
  get_xp_status: "Checking XP status",
  send_whatsapp: "Sending WhatsApp message",
  search_obsidian: "Searching Obsidian vault",
  create_daily_note: "Creating daily note",
  remember_preference: "Learning preference",
  create_invoice: "Creating invoice",
  list_invoices: "Listing invoices",
  update_invoice_status: "Updating invoice status",
  scrape_url: "Scraping web page",
  generate_code: "Generating code",
  get_analytics: "Loading analytics",
  log_health: "Logging health entry",
  get_health_summary: "Loading health summary",
};
