module.exports = {
  apps: [
    {
      name: "bee-telegram",
      script: "/var/www/bee-brain/agent/venv/bin/python3",
      args: "-m tg_bot.bot",
      cwd: "/var/www/bee-brain/agent",
      env: {
        BEE_BRAIN_PATH: "/var/www/bee-brain",
        PYTHONPATH: "/var/www/bee-brain/agent",
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      log_file: "/var/log/bee-telegram.log",
      error_file: "/var/log/bee-telegram-error.log",
      out_file: "/var/log/bee-telegram-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_memory_restart: "200M",
    },
    {
      name: "bee-vault-api",
      script: "/var/www/bee-brain/agent/venv/bin/python3",
      args: "-m uvicorn api.app:app --host 0.0.0.0 --port 3003",
      cwd: "/var/www/bee-brain/agent",
      env: {
        BEE_BRAIN_PATH: "/var/www/bee-brain",
        PYTHONPATH: "/var/www/bee-brain/agent",
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      log_file: "/var/log/bee-vault-api.log",
      error_file: "/var/log/bee-vault-api-error.log",
      out_file: "/var/log/bee-vault-api-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_memory_restart: "200M",
    },
  ],
};
